CREATE DATABASE IF NOT EXISTS CONTROLCONDUCTORES;
USE CONTROLCONDUCTORES;
CREATE TABLE IF NOT EXISTS LICENCIAS (
LICENCIA VARCHAR(20) PRIMARY KEY,
DNI VARCHAR(20) NOT NULL,
NOMBRE_APELLIDOS VARCHAR(100) NOT NULL,
MATRICULA VARCHAR(100)  UNIQUE,
MARCA_MODELO VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
NUMERO_PATRONAL VARCHAR(50)
);
DROP TABLE LICENCIAS;
CREATE TABLE IF NOT EXISTS conductores (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre_apellidos VARCHAR(255) NOT NULL,
    dni VARCHAR(20) NOT NULL,
    direccion VARCHAR(255) NOT NULL,
    codigo_postal VARCHAR(10) NOT NULL,
    email VARCHAR(100) NOT NULL,
    numero_seguridad_social VARCHAR(30) NOT NULL,
    LICENCIA VARCHAR(20),
    CONSTRAINT fk_licencia FOREIGN KEY (licencia) REFERENCES LICENCIAS(LICENCIA) ON DELETE SET NULL
);
DROP TABLE CONDUCTORES;
INSERT INTO licencias (LICENCIA, DNI, NOMBRE_APELLIDOS, MATRICULA, MARCA_MODELO, EMAIL, NUMERO_PATRONAL) VALUES
('LIC123', '12345678A', 'Juan Pérez', '1234ABC', 'Toyota Corolla', 'juan@example.com', '12345');
INSERT INTO conductores (NOMBRE_APELLIDOS, DNI, DIRECCION, CODIGO_POSTAL, EMAIL, NUMERO_SEGURIDAD_SOCIAL) VALUES
( 'Luis Martínez', '99887766D', 'Calle Falsa 123', '28001', 'luis@example.com', 'SS001');

SELECT * FROM LICENCIAS;
SELECT * FROM CONDUCTORES;
